In [1]:
import sys

assert sys.version_info >= (3,10)

In [2]:
from packaging.version import Version
import sklearn

assert Version(sklearn.__version__) >= Version('1.6.1')

In [3]:
import torch

assert Version(torch.__version__) >= Version('2.6.0')

In [4]:
IS_COLAB = "google.colab" in sys.modules
IS_KAGGLE = "kaggle_secrets" in sys.modules

In [5]:
import matplotlib.pyplot as plt

plt.rc('font', size=14)
plt.rc('axes', labelsize=14, titlesize=14)
plt.rc('legend', fontsize = 14)
plt.rc('ytick' , labelsize=10)
plt.rc('xtick', labelsize=10)

In [6]:
import torch

X = torch.tensor([[1.0, 4.0, 7.0], [2.0, 3.0, 6.0]])
X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [7]:
X.shape

torch.Size([2, 3])

In [8]:
X.dtype

torch.float32

In [9]:
X[0,1]

tensor(4.)

In [10]:
X[:, 2]

tensor([7., 6.])

In [11]:
10 * (X + 1.0)

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [12]:
X.exp()

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])

In [13]:
X.mean()

tensor(3.8333)

In [14]:
X.max(dim=0)

torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))

In [15]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]])

In [16]:
import numpy as np

X.numpy()

array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [17]:
torch.tensor(np.array([[1., 4., 7.], [ 2., 3.,6.]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

In [18]:
torch.FloatTensor(np.array([[1., 4., 7.], [2., 3., 6.]]))

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [19]:
X2_np = np.array([[1., 4., 7.], [2., 3., 6]])
X2 = torch.from_numpy(X2_np)
X2_np[0, 1] = 88
X2

tensor([[ 1., 88.,  7.],
        [ 2.,  3.,  6.]], dtype=torch.float64)

In [20]:
X[:, 1] = -99
X

tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In [21]:
X.relu_()
X

tensor([[1., 0., 7.],
        [2., 0., 6.]])

In [22]:
functions = lambda mod: set(f for f in dir(mod) if callable(getattr(mod,f)))
', '.join(sorted(functions(torch) & functions(np)))

'__getattr__, abs, absolute, acos, acosh, add, all, allclose, amax, amin, angle, any, arange, arccos, arccosh, arcsin, arcsinh, arctan, arctan2, arctanh, argmax, argmin, argsort, argwhere, asarray, asin, asinh, atan, atan2, atanh, atleast_1d, atleast_2d, atleast_3d, bincount, bitwise_and, bitwise_left_shift, bitwise_not, bitwise_or, bitwise_right_shift, bitwise_xor, broadcast_shapes, broadcast_to, can_cast, ceil, clip, column_stack, concat, concatenate, conj, copysign, corrcoef, cos, cosh, count_nonzero, cov, cross, cumprod, cumsum, deg2rad, diag, diagflat, diagonal, diff, divide, dot, dsplit, dstack, dtype, einsum, empty, empty_like, equal, exp, exp2, expm1, eye, finfo, fix, flip, fliplr, flipud, float_power, floor, floor_divide, fmax, fmin, fmod, frexp, from_dlpack, frombuffer, full, full_like, gcd, gradient, greater, greater_equal, heaviside, histogram, histogramdd, hsplit, hstack, hypot, i0, iinfo, imag, inner, isclose, isfinite, isin, isinf, isnan, isneginf, isposinf, isreal, kron

In [23]:
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

device

'cuda'

In [24]:
M = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
M = M.to(device)
M.device

device(type='cuda', index=0)

In [25]:
M  = torch.tensor([[1., 2., 3.], [4., 5., 6.]], device=device)

In [26]:
R = M @ M.T
R

tensor([[14., 32.],
        [32., 77.]], device='cuda:0')

In [27]:
torch.rand((1000, 1000))
M @ M.T
%timeit M @ M.T



15.5 μs ± 1.18 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [28]:
M.dtype

torch.float32

In [29]:
M = M.to(device)
M @ M.T
%timeit M @ M.T

14.9 μs ± 646 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [30]:
x = torch.tensor(5.0, requires_grad=True)
f = x **2
f

tensor(25., grad_fn=<PowBackward0>)

In [31]:
f.backward()
x.grad

tensor(10.)

In [32]:
learning_rate = 0.1
with torch.no_grad():
    x -= learning_rate * x.grad

In [33]:
x

tensor(4., requires_grad=True)

In [34]:
learning_rate  = 0.1
x = torch.tensor(5.0, requires_grad=True)
for iteration in range(100):
    f = x ** 2
    f.backward()
    with torch.no_grad():
        x -= learning_rate * x.grad
    x.grad.zero_()

In [35]:
x

tensor(1.0185e-09, requires_grad=True)

In [36]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

housing = fetch_california_housing()
X_train_full, X_test, y_train_full, y_test = train_test_split(
    housing.data, housing.target, random_state=42
)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, random_state=42
)


In [37]:
X_train = torch.FloatTensor(X_train)
X_valid = torch.FloatTensor(X_valid)
X_test = torch.FloatTensor(X_test)
means = X_train.mean(dim=0, keepdims=True)
stds = X_train.std(dim=0, keepdims=True)
X_train = (X_train - means) / stds
X_valid = (X_valid - means) / stds
X_test = (X_test - means) / stds
stds.shape


torch.Size([1, 8])

In [38]:
y_train = torch.FloatTensor(y_train). view(-1, 1)
y_valid = torch.FloatTensor(y_valid).view(-1, 1)
y_test = torch.FloatTensor(y_test).view(-1, 1)

In [39]:
torch.manual_seed(42)
n_features = X_train.shape[1]
w = torch.randn((n_features, 1), requires_grad=True)
b = torch.tensor(0., requires_grad=True)

In [40]:
learning_rate = 0.4
n_epochs  = 20
for epoch in range(n_epochs):
    y_pred = X_train @ w + b
    loss = ((y_pred - y_train) ** 2).mean()
    loss.backward()
    with torch.no_grad():
        b -= learning_rate * b.grad
        w -= learning_rate * w.grad
        b.grad.zero_()
        w.grad.zero_()
    print(f"Epoch { epoch + 1} / {n_epochs}, Loss: {loss.item()}")

Epoch 1 / 20, Loss: 16.158456802368164
Epoch 2 / 20, Loss: 4.879360675811768
Epoch 3 / 20, Loss: 2.2552263736724854
Epoch 4 / 20, Loss: 1.330762267112732
Epoch 5 / 20, Loss: 0.9680696129798889
Epoch 6 / 20, Loss: 0.8142682313919067
Epoch 7 / 20, Loss: 0.7417050004005432
Epoch 8 / 20, Loss: 0.7020705342292786
Epoch 9 / 20, Loss: 0.6765922904014587
Epoch 10 / 20, Loss: 0.6577968597412109
Epoch 11 / 20, Loss: 0.6426154971122742
Epoch 12 / 20, Loss: 0.6297225952148438
Epoch 13 / 20, Loss: 0.61849445104599
Epoch 14 / 20, Loss: 0.6085970997810364
Epoch 15 / 20, Loss: 0.5998218655586243
Epoch 16 / 20, Loss: 0.5920188426971436
Epoch 17 / 20, Loss: 0.5850692987442017
Epoch 18 / 20, Loss: 0.5788735151290894
Epoch 19 / 20, Loss: 0.5733454823493958
Epoch 20 / 20, Loss: 0.5684101581573486


In [41]:
X_new = X_test[:3]
with torch.no_grad():
    y_pred = X_new @ w + b

In [42]:
y_pred

tensor([[0.8916],
        [1.6480],
        [2.6577]])

Linear Regression Using PyTorch's High-Level API

In [43]:
import torch.nn as nn

torch.manual_seed(42)
model = nn.Linear(in_features=n_features, out_features=1)

In [44]:
model.bias

Parameter containing:
tensor([0.3117], requires_grad=True)

In [45]:
model.weight

Parameter containing:
tensor([[ 0.2703,  0.2935, -0.0828,  0.3248, -0.0775,  0.0713, -0.1721,  0.2076]],
       requires_grad=True)

In [46]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[ 0.2703,  0.2935, -0.0828,  0.3248, -0.0775,  0.0713, -0.1721,  0.2076]],
       requires_grad=True)
Parameter containing:
tensor([0.3117], requires_grad=True)


In [47]:
model(X_train[:2])

tensor([[-0.4718],
        [ 0.1131]], grad_fn=<AddmmBackward0>)

In [48]:
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
mse  = nn.MSELoss()

In [49]:
def train_bgd(model, optimizer, criterion, X_train, y_train, n_epochs):
    for epoch in range(n_epochs):
        y_pred = model(X_train)
        loss = criterion(y_pred, y_train)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        print(f"Epoch {epoch + 1}/{n_epochs}, Loss: {loss.item()}")

In [50]:
train_bgd(model, optimizer, mse, X_train, y_train, n_epochs)

Epoch 1/20, Loss: 4.3378496170043945
Epoch 2/20, Loss: 0.7802932858467102
Epoch 3/20, Loss: 0.6253840327262878
Epoch 4/20, Loss: 0.6060433983802795
Epoch 5/20, Loss: 0.595629870891571
Epoch 6/20, Loss: 0.5873566269874573
Epoch 7/20, Loss: 0.5802990198135376
Epoch 8/20, Loss: 0.5741382241249084
Epoch 9/20, Loss: 0.5687100291252136
Epoch 10/20, Loss: 0.5639079213142395
Epoch 11/20, Loss: 0.5596510767936707
Epoch 12/20, Loss: 0.555873692035675
Epoch 13/20, Loss: 0.5525193810462952
Epoch 14/20, Loss: 0.5495391488075256
Epoch 15/20, Loss: 0.5468899011611938
Epoch 16/20, Loss: 0.5445338487625122
Epoch 17/20, Loss: 0.5424376726150513
Epoch 18/20, Loss: 0.5405716300010681
Epoch 19/20, Loss: 0.5389096736907959
Epoch 20/20, Loss: 0.5374288558959961


In [51]:
X_new = X_test[:3]
with torch.no_grad():
    y_pred = model(X_new)

y_pred

tensor([[0.8061],
        [1.7116],
        [2.6973]])

Implementing a Regression MLP

In [52]:
torch.manual_seed(42)
model = nn.Sequential(
    nn.Linear(n_features, 50),
    nn.ReLU(),
    nn.Linear(50, 40),
    nn.ReLU(),
    nn.Linear(40, 1)
)

In [53]:
learning_rate = 0.1
optimizer = torch.optim. SGD(model.parameters(), lr=learning_rate)
mse = nn.MSELoss()
train_bgd(model, optimizer, mse, X_train, y_train, n_epochs)

Epoch 1/20, Loss: 5.045480251312256
Epoch 2/20, Loss: 2.0523130893707275
Epoch 3/20, Loss: 1.00398850440979
Epoch 4/20, Loss: 0.8570139408111572
Epoch 5/20, Loss: 0.7740675806999207
Epoch 6/20, Loss: 0.7225848436355591
Epoch 7/20, Loss: 0.689372718334198
Epoch 8/20, Loss: 0.6669032573699951
Epoch 9/20, Loss: 0.6507738828659058
Epoch 10/20, Loss: 0.6383934617042542
Epoch 11/20, Loss: 0.6281994581222534
Epoch 12/20, Loss: 0.6193399429321289
Epoch 13/20, Loss: 0.6113173365592957
Epoch 14/20, Loss: 0.6038705706596375
Epoch 15/20, Loss: 0.5968307852745056
Epoch 16/20, Loss: 0.5901118516921997
Epoch 17/20, Loss: 0.583646833896637
Epoch 18/20, Loss: 0.5774063467979431
Epoch 19/20, Loss: 0.5713555216789246
Epoch 20/20, Loss: 0.565444827079773


Implementin Mini-Batch Gradient Descent
using DataLoaders

In [54]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [55]:
torch.manual_seed(42)
model = nn.Sequential(
    nn.Linear(n_features, 50), nn.ReLU(),
              nn.Linear(50,40), nn.ReLU(),
              nn.Linear(40, 1))

model = model.to(device)

learning_rate = 0.02
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
mse = nn.MSELoss()

In [56]:
def train(model, optimizer, criterion, train_loader, n_epochs):
    model.train()
    for epoch in range(n_epochs):
        total_loss = 0
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            loss = criterion(y_pred, y_batch)
            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()

        mean_loss = total_loss / len(train_loader)
        print(f"Epoch: {epoch + 1}/{n_epochs}, Loss: {mean_loss:.4f}")

In [57]:
train(model, optimizer, mse,train_loader, n_epochs)

Epoch: 1/20, Loss: 0.5900
Epoch: 2/20, Loss: 0.4046
Epoch: 3/20, Loss: 0.3801
Epoch: 4/20, Loss: 0.3629
Epoch: 5/20, Loss: 0.3529
Epoch: 6/20, Loss: 0.3519
Epoch: 7/20, Loss: 0.3408
Epoch: 8/20, Loss: 0.3426
Epoch: 9/20, Loss: 0.3406
Epoch: 10/20, Loss: 0.3379
Epoch: 11/20, Loss: 0.3303
Epoch: 12/20, Loss: 0.3263
Epoch: 13/20, Loss: 0.3242
Epoch: 14/20, Loss: 0.3235
Epoch: 15/20, Loss: 0.3189
Epoch: 16/20, Loss: 0.3151
Epoch: 17/20, Loss: 0.3121
Epoch: 18/20, Loss: 0.3111
Epoch: 19/20, Loss: 0.3086
Epoch: 20/20, Loss: 0.3061


Model Evaluation

In [58]:
def evaluate(model, data_loader, metric_fn, aggregate_fn = torch.mean):
    model.eval()
    metrics = []
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            metric = metric_fn(y_pred, y_batch)
            metrics.append(metric)
    return aggregate_fn(torch.stack(metrics))


In [59]:
valid_dataset = TensorDataset(X_valid, y_valid)
valid_loader = DataLoader(valid_dataset, batch_size=32)
valid_mse = evaluate(model, valid_loader, mse)
valid_mse

tensor(0.2944, device='cuda:0')

def rmse(y_pred, y_true):
    return ((y_pred - y_true) ** 2).mean().sqrt()

evaluate(model, valid_loader, rmse)

In [60]:
def rmse(y_pred, y_true):
    return ((y_pred - y_true) ** 2).mean().sqrt()

evaluate(model, valid_loader, rmse)

tensor(0.5291, device='cuda:0')

In [61]:
valid_mse.sqrt()


tensor(0.5426, device='cuda:0')

In [62]:
evaluate(model, valid_loader, mse,
         aggregate_fn=lambda metrics: torch.sqrt(torch.mean(metrics)))

tensor(0.5426, device='cuda:0')

In [63]:
import torchmetrics

def evaluate_tm(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for X_batch, y_batch in data_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            metric.update(y_pred, y_batch)
    return metric.compute()

In [64]:
rmse =  torchmetrics.MeanSquaredError(squared=False).to(device)
evaluate_tm(model, valid_loader, rmse)

tensor(0.5427, device='cuda:0')

In [65]:
def train2(model, optimizer, criterion, metric, train_loader, valid_loader,
           n_epochs):
    history = {"train_losses":  [],
               "train_metrics": [],
               "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.
        metric.reset()
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            y_pred = model(X_batch)
            loss = criterion(y_pred, y_batch)
            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            metric.update(y_pred, y_batch)

        mean_loss = total_loss / len(train_loader)
        history["train_losses"].append(mean_loss)
        history["train_metrics"].append(metric.compute().item())
        history["valid_metrics"].append(
            evaluate_tm(model, valid_loader, metric).item()
        )
        print(f"Epoch: {epoch + 1}/{n_epochs},"
              f"train loss: {history['train_losses'][-1]: .4f},"
              f"train metric: {history['train_metrics'][-1]:.4f},"
              f"valid metric: {history['valid_metrics'][-1]:.4f}")
    return history

torch.manual_seed(42)
learning_rate = 0.01
model = nn.Sequential(
    nn.Linear(n_features, 50), nn.ReLU(),
    nn.Linear(50, 40), nn.ReLU(),
    nn.Linear(40, 30), nn.ReLU(),
    nn.Linear(30, 1)
)
model = model.to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=0)
mse = nn.MSELoss()
rmse = torchmetrics.MeanSquaredError(squared=False).to(device)
history = train2(model, optimizer, mse, rmse, train_loader, valid_loader,
                 n_epochs)

plt.plot(np.arange(n_epochs) + 0.5, history['train_metrics'], ".--",
         label="Training")
plt.plot(np.arange(n_epochs) + 1.0, history["valid_metrics"], ".-",
         label = "Validation")
plt.xlabel("Epoch")
plt.ylabel("RMSE")
plt.grid()
plt.title("Learning curves")
plt.axis([0.5, 20, 0.4, 1.0])
plt.legend()
plt.show()

Epoch: 1/20,train loss:  0.7826,train metric: 0.8847,valid metric: 0.6690
Epoch: 2/20,train loss:  0.4362,train metric: 0.6605,valid metric: 0.6099
Epoch: 3/20,train loss:  0.3930,train metric: 0.6269,valid metric: 0.6145
Epoch: 4/20,train loss:  0.3759,train metric: 0.6132,valid metric: 0.5963
Epoch: 5/20,train loss:  0.3649,train metric: 0.6040,valid metric: 0.5911
Epoch: 6/20,train loss:  0.3598,train metric: 0.5999,valid metric: 0.5965
Epoch: 7/20,train loss:  0.3530,train metric: 0.5941,valid metric: 0.6061
Epoch: 8/20,train loss:  0.3495,train metric: 0.5911,valid metric: 0.6043
Epoch: 9/20,train loss:  0.3455,train metric: 0.5877,valid metric: 0.5723
Epoch: 10/20,train loss:  0.3415,train metric: 0.5844,valid metric: 0.6031
Epoch: 11/20,train loss:  0.3402,train metric: 0.5831,valid metric: 0.5891
Epoch: 12/20,train loss:  0.3362,train metric: 0.5799,valid metric: 0.5738


KeyboardInterrupt: 

Building Nonsequential Models Using Custom Modules

In [ ]:
class WideAndDeep(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.deep_stack = nn.Sequential(
            nn.Linear(n_features, 50), nn.ReLU(),
            nn.Linear(50, 40), nn.ReLU(),
            nn.Linear(40, 30), nn.ReLU(),

        )
        self.output_layer = nn.Linear(30 + n_features, 1)

    def forward(self, X):
        deep_output = self.deep_stack(X)
        wide_and_deep = torch.concat([X, deep_output], dim=1)
        return self.output_layer(wide_and_deep)

In [ ]:
torch.manual_seed(42)
model = WideAndDeep(n_features).to(device)
learning_rate =0.002

In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=0)
mse = nn.MSELoss()
rmse = torchmetrics.MeanSquaredError(squared=False).to(device)
history = train2(model, optimizer, mse, rmse, train_loader, valid_loader,
                 n_epochs)

Epoch: 1/20,train loss:  1.7802,train metric: 1.3344,valid metric: 0.8690
Epoch: 2/20,train loss:  0.6201,train metric: 0.7875,valid metric: 0.9492
Epoch: 3/20,train loss:  0.5900,train metric: 0.7682,valid metric: 0.7331
Epoch: 4/20,train loss:  0.5607,train metric: 0.7488,valid metric: 0.7771
Epoch: 5/20,train loss:  0.5408,train metric: 0.7353,valid metric: 0.7967
Epoch: 6/20,train loss:  0.5244,train metric: 0.7241,valid metric: 0.7098
Epoch: 7/20,train loss:  0.5070,train metric: 0.7119,valid metric: 0.7419
Epoch: 8/20,train loss:  0.4941,train metric: 0.7030,valid metric: 0.6750
Epoch: 9/20,train loss:  0.4798,train metric: 0.6928,valid metric: 0.6762
Epoch: 10/20,train loss:  0.4657,train metric: 0.6825,valid metric: 0.6678
Epoch: 11/20,train loss:  0.4538,train metric: 0.6736,valid metric: 0.6617
Epoch: 12/20,train loss:  0.4441,train metric: 0.6665,valid metric: 0.6651
Epoch: 13/20,train loss:  0.4328,train metric: 0.6580,valid metric: 0.6803
Epoch: 14/20,train loss:  0.4232,t

In [ ]:
class WideAndDeepV2(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.deep_stack = nn.Sequential(
            nn.Linear(n_features - 2, 50), nn.ReLU(),
            nn.Linear(50, 40), nn.ReLU(),
            nn.Linear(40, 30), nn.ReLU()
        )
        self.output_layer = nn.Linear(30 + 5, 1)

    def forward(self, X):
        X_wide = X[:, :5]
        X_deep = X[:, 2:]
        deep_output = self.deep_stack(X_deep)
        wide_and_deep = torch.concat([X_wide, deep_output], dim=1)
        return self.output_layer(wide_and_deep)

In [ ]:
torch.manual_seed(42)
model = WideAndDeepV2(n_features).to(device)

In [ ]:
learning_rate = 0.002
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=0)
mse = nn.MSELoss()
rmse = torchmetrics.MeanSquaredError(squared=False).to(device)
history = train2(model, optimizer, mse, rmse, train_loader, valid_loader,
n_epochs)

Epoch: 1/20,train loss:  1.8482,train metric: 1.3598,valid metric: 0.9100
Epoch: 2/20,train loss:  0.6282,train metric: 0.7927,valid metric: 0.8028
Epoch: 3/20,train loss:  0.5763,train metric: 0.7591,valid metric: 0.7567
Epoch: 4/20,train loss:  0.5413,train metric: 0.7356,valid metric: 0.7290
Epoch: 5/20,train loss:  0.5099,train metric: 0.7142,valid metric: 0.7011
Epoch: 6/20,train loss:  0.4841,train metric: 0.6958,valid metric: 0.6816
Epoch: 7/20,train loss:  0.4656,train metric: 0.6824,valid metric: 0.6670
Epoch: 8/20,train loss:  0.4526,train metric: 0.6728,valid metric: 0.6576
Epoch: 9/20,train loss:  0.4438,train metric: 0.6662,valid metric: 0.6539
Epoch: 10/20,train loss:  0.4380,train metric: 0.6618,valid metric: 0.6498
Epoch: 11/20,train loss:  0.4326,train metric: 0.6577,valid metric: 0.6470
Epoch: 12/20,train loss:  0.4284,train metric: 0.6546,valid metric: 0.6447
Epoch: 13/20,train loss:  0.4253,train metric: 0.6521,valid metric: 0.6452
Epoch: 14/20,train loss:  0.4216,t

Building Models with Multiple inputs

In [ ]:
class WideAndDeepV3(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.deep_stack = nn.Sequential(
            nn.Linear(n_features -2, 50), nn.ReLU(),
            nn.Linear(50, 40), nn.ReLU(),
            nn.Linear(40, 30), nn.ReLU()
                                        )
        self.output_layer = nn.Linear(30 + 5, 1)

    def forward(self, X_wide, X_deep):
        deep_output = self.deep_stack(X_deep)
        wide_and_deep = torch.concat([X_wide, deep_output], dim=1)
        return self.output_layer(wide_and_deep)
    

In [ ]:
torch.manual_seed(42)
train_data_wd = TensorDataset(X_train[:, :5], X_train[:, 2:], y_train)
train_loader_wd = DataLoader(train_data_wd, batch_size=32, shuffle=True)
valid_data_wd  = TensorDataset(X_valid[:, :5],X_valid[:, 2:], y_valid)
valid_loader_wd = DataLoader(valid_data_wd, batch_size=32)
test_data_wd = TensorDataset(X_test[:, :5], X_test[:, 2:], y_test)
test_loader_wd = DataLoader(test_data_wd, batch_size=32)

In [ ]:
def evaluate_multi_in(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for X_batch_wide, X_batch_deep, y_batch in data_loader:
            X_batch_wide = X_batch_wide.to(device)
            X_batch_deep  = X_batch_deep.to(device)
            y_batch = y_batch.to(device)
            y_pred = model(X_batch_wide, X_batch_deep)
            metric.update(y_pred, y_batch)
    return metric.compute()

def train_multi_in(model, optimizer, criterion, metric, train_loader,
                   valid_loader, n_epochs):
    history = {"train_losses": [],
               "train_metrics": [],
               "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.
        metric.reset()
        for *X_batch_inputs, y_batch in train_loader:
            model.train()
            X_batch_inputs = [X.to(device) for X in X_batch_inputs]
            y_batch = y_batch.to(device)
            y_pred = model(*X_batch_inputs)
            loss = criterion(y_pred, y_batch)
            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            metric.update(y_pred, y_batch)
        mean_loss = total_loss / len(train_loader)
        history["train_losses"].append(mean_loss)
        history["train_metrics"].append(metric.compute().item())
        history["valid_metrics"].append(
            evaluate_multi_in(model, valid_loader, metric).item())
        print(f"Epoch: {epoch + 1}/{n_epochs},"
                f"train loss: {history['train_losses'][-1]:.4f},"
                f"train_metric: {history['train_metrics'][-1]:.4f},"
            f"valid metric: {history['valid_metrics'][-1]: .4f}")

    return history

torch.manual_seed(42)
learning_rate = 0.01
model = WideAndDeepV3(n_features).to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=0)
mse = nn.MSELoss()
rmse = torchmetrics.MeanSquaredError(squared=False).to(device)
history = train_multi_in(model, optimizer, mse, rmse, train_loader_wd,
                            valid_loader_wd, n_epochs)

Epoch: 1/20,train loss: 0.8366,train_metric: 0.9148,valid metric:  0.6892
Epoch: 2/20,train loss: 0.4627,train_metric: 0.6803,valid metric:  0.6455
Epoch: 3/20,train loss: 0.4319,train_metric: 0.6572,valid metric:  0.6374
Epoch: 4/20,train loss: 0.4259,train_metric: 0.6525,valid metric:  0.6512
Epoch: 5/20,train loss: 0.4120,train_metric: 0.6420,valid metric:  0.6305
Epoch: 6/20,train loss: 0.4040,train_metric: 0.6356,valid metric:  0.6287
Epoch: 7/20,train loss: 0.4005,train_metric: 0.6330,valid metric:  0.6252
Epoch: 8/20,train loss: 0.3976,train_metric: 0.6306,valid metric:  0.6158
Epoch: 9/20,train loss: 0.3883,train_metric: 0.6230,valid metric:  0.7407
Epoch: 10/20,train loss: 0.3866,train_metric: 0.6218,valid metric:  0.6063
Epoch: 11/20,train loss: 0.3752,train_metric: 0.6125,valid metric:  0.5974
Epoch: 12/20,train loss: 0.3704,train_metric: 0.6087,valid metric:  0.5887
Epoch: 13/20,train loss: 0.3677,train_metric: 0.6063,valid metric:  0.5982
Epoch: 14/20,train loss: 0.3604,tr

In [ ]:
class WideAndDeepDataset(torch.utils.data.Dataset):
    def __init__(self, X_wide, X_deep, y):
        self.X_wide = X_wide
        self.X_deep = X_deep
        self.y = y

    def __len__(self):
        return len(self.y)
    
    def __getitem__(self, idx):
        input_dict = {"X_wide": self.X_wide[idx],
                      "X_deep": self.X_deep[idx]}
        return input_dict, self.y[idx]

In [ ]:
torch.manual_seed(42)
train_data_named = WideAndDeepDataset(
    X_wide = X_train[:, :5], X_deep = X_train[:, 2:], y = y_train)
train_loader_named = DataLoader(train_data_named, batch_size=32, shuffle=True)
test_data_named = WideAndDeepDataset(
    X_wide = X_test[:, :5], X_deep = X_test[:, 2:], y = y_test)
test_loader_named = DataLoader(test_data_named, batch_size=32)
valid_data_named = WideAndDeepDataset(
    X_wide = X_valid[:, :5], X_deep= X_valid[:, 2:], y= y_valid)
valid_loader_named = DataLoader(valid_data_named, batch_size=32)

In [ ]:
def evaluate_named(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for inputs, y_batch in data_loader:
            inputs = {name: X.to(device) for name,X  in inputs.items()}
            y_batch = y_batch.to(device)
            y_pred = model(X_wide=inputs['X_wide'], X_deep = inputs["X_deep"])
            metric.update(y_pred, y_batch)
    return metric.compute()

def train_named(model, optimizer, criterion, metric, train_loader,
                valid_loader, n_epochs):
    history = {"train_losses": [],
               "train_metrics": [],
               "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.
        metric.reset()
        for inputs, y_batch in train_loader:
            inputs = {name: X.to(device) for name,X in inputs.items()}
            y_batch =y_batch.to(device)
            y_pred = model(X_wide = inputs["X_wide"], X_deep  = inputs["X_deep"])
            loss = criterion(y_pred , y_batch)
            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad() 
            metric.update(y_pred, y_batch)
        mean_loss = total_loss/ len(train_loader)
        history["train_losses"].append(mean_loss)
        history["train_metrics"].append(metric.compute().item())
        history["valid_metrics"].append(evaluate_named(model, valid_loader_named, metric).item())
        print(f" Epoch {epoch + 1}/{n_epochs},"
        f"train loss: {history["train_losses"][-1]:.4f},"
        f"train metrics: {history["train_metrics"][-1]:.4f},"
        f"valid metric: {history["valid_metrics"][-1]:.4f}")
    return history

torch.manual_seed(42)
learning_rate = 0.01
model = WideAndDeepV3(n_features).to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=0)
mse = nn.MSELoss()
rmse = torchmetrics.MeanSquaredError(squared=False).to(device)
history = train_named(model, optimizer, mse, rmse, train_loader_named,
valid_loader_named, n_epochs)

 Epoch 1/20,train loss: 0.8366,train metrics: 0.9148,valid metric: 0.6892
 Epoch 2/20,train loss: 0.4627,train metrics: 0.6803,valid metric: 0.6455
 Epoch 3/20,train loss: 0.4319,train metrics: 0.6572,valid metric: 0.6374
 Epoch 4/20,train loss: 0.4259,train metrics: 0.6525,valid metric: 0.6512
 Epoch 5/20,train loss: 0.4120,train metrics: 0.6420,valid metric: 0.6305
 Epoch 6/20,train loss: 0.4040,train metrics: 0.6356,valid metric: 0.6287
 Epoch 7/20,train loss: 0.4005,train metrics: 0.6330,valid metric: 0.6252
 Epoch 8/20,train loss: 0.3976,train metrics: 0.6306,valid metric: 0.6158
 Epoch 9/20,train loss: 0.3883,train metrics: 0.6230,valid metric: 0.7407
 Epoch 10/20,train loss: 0.3866,train metrics: 0.6218,valid metric: 0.6063
 Epoch 11/20,train loss: 0.3752,train metrics: 0.6125,valid metric: 0.5974
 Epoch 12/20,train loss: 0.3704,train metrics: 0.6087,valid metric: 0.5887
 Epoch 13/20,train loss: 0.3677,train metrics: 0.6063,valid metric: 0.5982
 Epoch 14/20,train loss: 0.3604,tr

Building Models with Multiple Outputs

In [ ]:
class WideAndDeepV4(nn.Module):
    def __init__(self, n_features):
        super().__init__()
        self.deep_stack = nn.Sequential(
            nn.Linear(n_features - 2, 50), nn.ReLU(),
            nn.Linear(50, 40), nn.ReLU(),
            nn.Linear(40, 30), nn.ReLU(),
        )
        self.output_layer = nn.Linear(30 + 5, 1)
        self.aux_output_layer = nn.Linear(30, 1)

    def forward(self, X_wide, X_deep):
        deep_output = self.deep_stack(X_deep)
        wide_and_deep = torch.concat([X_wide, deep_output], dim=1)
        main_output = self.output_layer(wide_and_deep)
        aux_output = self.aux_output_layer(deep_output)
        return main_output, aux_output

In [ ]:
import torchmetrics

def evaluate_multi_out(model, data_loader, metric):
    model.eval()
    metric.reset()
    with torch.no_grad():
        for inputs, y_batch in data_loader:
            inputs = {name: X.to(device) for name, X in inputs.items()}
            y_batch = y_batch.to(device)
            y_pred, _ = model(**inputs)
            metric.update(y_pred, y_batch)
    return metric.compute()

def train_multi_out(model, optimizer, criterion, metric, train_loader,
                    valid_loader, n_epochs):
    history = {"train_losses": [],
               "train_metrics": [],
               "valid_metrics": []}
    for epoch in range(n_epochs):
        total_loss = 0.
        metric.reset()
        for inputs, y_batch in train_loader:
            model.train()
            inputs = {name: X.to(device) for name, X in inputs.items()}
            y_batch  = y_batch.to(device)
            y_pred, y_pred_aux  = model(**inputs)
            main_loss = criterion(y_pred, y_batch)
            aux_loss = criterion(y_pred_aux, y_batch)
            loss = 0.8 * main_loss + 0.2 * aux_loss
            total_loss += loss.item()
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            metric.update(y_pred, y_batch)
        mean_loss = total_loss/ len(train_loader)
        history["train_losses"].append(mean_loss)
        history["train_metrics"].append(metric.compute().item())
        history["valid_metrics"].append(
            evaluate_multi_out(model, valid_loader, metric).item())
        print(f"Epoch {epoch + 1}/{n_epochs}, "
              f"train loss: {history['train_losses'][-1]:.4f}, "
              f"train metric: {history['train_metrics'][-1]:.4f}, "
              f"valid metric: {history['valid_metrics'][-1]:.4f}")
    return history

torch.manual_seed(42)
learning_rate = 0.01
model = WideAndDeepV4(n_features).to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=0)
mse = nn.MSELoss()
rmse = torchmetrics.MeanSquaredError(squared=False).to(device)
history = train_multi_out(model, optimizer, mse, rmse, train_loader_named,
                          valid_loader_named, n_epochs)


Epoch 1/20, train loss: 1.0693, train metric: 0.9506, valid metric: 0.7085
Epoch 2/20, train loss: 0.5817, train metric: 0.6946, valid metric: 0.6607
Epoch 3/20, train loss: 0.5010, train metric: 0.6581, valid metric: 0.6425
Epoch 4/20, train loss: 0.4690, train metric: 0.6497, valid metric: 0.6654
Epoch 5/20, train loss: 0.4503, train metric: 0.6420, valid metric: 0.6338
Epoch 6/20, train loss: 0.4387, train metric: 0.6373, valid metric: 0.6563
Epoch 7/20, train loss: 0.4315, train metric: 0.6330, valid metric: 0.6193
Epoch 8/20, train loss: 0.4249, train metric: 0.6302, valid metric: 0.6167
Epoch 9/20, train loss: 0.4116, train metric: 0.6202, valid metric: 0.6450
Epoch 10/20, train loss: 0.4085, train metric: 0.6198, valid metric: 0.5938
Epoch 11/20, train loss: 0.4073, train metric: 0.6196, valid metric: 0.5959
Epoch 12/20, train loss: 0.3914, train metric: 0.6077, valid metric: 0.6074
Epoch 13/20, train loss: 0.3847, train metric: 0.6033, valid metric: 0.5813
Epoch 14/20, train lo

Building an Image Classifier with Pytorch

Using Torchvision to load the Dataset

In [ ]:
import torchvision
import torchvision.transforms.v2 as T

toTensor = T.Compose([T.ToImage(), T.ToDtype(torch.float32, scale=True)])
train_and_valid_data = torchvision.datasets.FashionMNIST(
    root="datasets", train=True, download=True, transform=toTensor)
test_data = torchvision.datasets.FashionMNIST(
    root="datasets", train=False, download=True, transform=toTensor)

torch.manual_seed(42)
train_data, valid_data = torch.utils.data.random_split(
    train_and_valid_data, [55_000, 5_000]
)

100%|██████████| 26.4M/26.4M [00:13<00:00, 1.89MB/s]
100%|██████████| 29.5k/29.5k [00:00<00:00, 69.2kB/s]
100%|██████████| 4.42M/4.42M [00:14<00:00, 297kB/s] 
100%|██████████| 5.15k/5.15k [00:00<00:00, 24.0MB/s]


In [ ]:
torch.manual_seed(42)
train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
valid_loader = DataLoader(valid_data, batch_size=32)
test_loader = DataLoader(test_data, batch_size=32)

In [ ]:
X_sample, y_sample = train_data[0]

In [ ]:
X_sample.shape

torch.Size([1, 28, 28])

In [ ]:
X_sample.dtype

torch.float32

In [ ]:
train_and_valid_data.classes[y_sample]

'Ankle boot'

Building the Classifier

In [ ]:
class ImageClassifier(nn.Module):
    def __init__(self, n_inputs, n_hidden1, n_hidden2, n_classes):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Flatten(),
            nn.Linear(n_inputs, n_hidden1),nn.ReLU(),
            nn.Linear(n_hidden1, n_hidden2), nn.ReLU(),
            nn.Linear(n_hidden2, n_classes)

        )
    def forward(self, X):
        return self.mlp(X)

torch.manual_seed(42)
model = ImageClassifier(n_inputs = 1 * 28 * 28, n_hidden1=300, n_hidden2=100,n_classes=10).to(device)
xentropy = nn.CrossEntropyLoss()

In [ ]:
optimizer  = torch.optim.SGD(model.parameters(), lr=0.1)
accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=10).to(device)
_ = train2(model, optimizer, xentropy, accuracy, train_loader, valid_loader,n_epochs)

Epoch: 1/20,train loss:  0.6061,train metric: 0.7817,valid metric: 0.8432
Epoch: 2/20,train loss:  0.4058,train metric: 0.8498,valid metric: 0.8424
Epoch: 3/20,train loss:  0.3632,train metric: 0.8652,valid metric: 0.8482
Epoch: 4/20,train loss:  0.3352,train metric: 0.8764,valid metric: 0.8642
Epoch: 5/20,train loss:  0.3149,train metric: 0.8836,valid metric: 0.8784
Epoch: 6/20,train loss:  0.2991,train metric: 0.8875,valid metric: 0.8634
Epoch: 7/20,train loss:  0.2856,train metric: 0.8932,valid metric: 0.8812
Epoch: 8/20,train loss:  0.2745,train metric: 0.8962,valid metric: 0.8752
Epoch: 9/20,train loss:  0.2641,train metric: 0.9007,valid metric: 0.8822
Epoch: 10/20,train loss:  0.2524,train metric: 0.9044,valid metric: 0.8748
Epoch: 11/20,train loss:  0.2456,train metric: 0.9069,valid metric: 0.8866
Epoch: 12/20,train loss:  0.2359,train metric: 0.9107,valid metric: 0.8890
Epoch: 13/20,train loss:  0.2293,train metric: 0.9122,valid metric: 0.8842
Epoch: 14/20,train loss:  0.2216,t

In [ ]:
model.eval()
X_new, y_new = next(iter(valid_loader))
X_new = X_new[:3].to(device)
with torch.no_grad():
    y_pred_logits = model(X_new)
y_pred = y_pred_logits.argmax(dim=1)
y_pred

tensor([7, 4, 2], device='cuda:0')

In [ ]:
[train_and_valid_data.classes[index] for index in y_pred]

['Sneaker', 'Coat', 'Pullover']

In [ ]:
y_new[:3]

tensor([7, 4, 2])

In [ ]:
import torch.nn.functional as F

y_proba = F.softmax(y_pred_logits, dim=1)
if device == 'mps':
    y_proba = y_proba.cpu()
y_proba.round(decimals=3)

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9600, 0.0000,
         0.0400],
        [0.0000, 0.0000, 0.0040, 0.0000, 0.9960, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0030, 0.0010, 0.6910, 0.0050, 0.1380, 0.0000, 0.1580, 0.0000, 0.0040,
         0.0000]], device='cuda:0')

In [ ]:
y_top4_values, y_top4_indices = torch.topk(y_pred_logits, k=4, dim=1)
y_top4_probas = F.softmax(y_top4_values, dim=1)
if device == "mps":
    y_top4_probas = y_top4_probas.cpu()
y_top4_probas.round(decimals=3)

tensor([[0.9600, 0.0400, 0.0000, 0.0000],
        [0.9960, 0.0040, 0.0000, 0.0000],
        [0.6970, 0.1590, 0.1390, 0.0050]], device='cuda:0')

In [ ]:
y_top4_indices

tensor([[7, 9, 5, 1],
        [4, 2, 6, 8],
        [2, 6, 4, 3]], device='cuda:0')

In [ ]:
sum([param.numel() for param in model.parameters()])

266610

Hyperparameter Tuning using Optuna

In [ ]:
import optuna
import tqdm as notebook_tqdm

def objective(trial):
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-1, log=True)
    n_hidden = trial.suggest_int("n_hidden", 20, 300)
    model = ImageClassifier(n_inputs=1 * 28 *28, n_hidden1=n_hidden,
                            n_hidden2=n_hidden, n_classes=10).to(device)
    optimizer  = torch.optim.SGD(model.parameters(), lr=learning_rate)
    xentropy = nn.CrossEntropyLoss()
    accuracy = torchmetrics.Accuracy(task = "multiclass", num_classes=10)
    accuracy = accuracy.to(device)
    history = train2(model, optimizer, xentropy,accuracy, train_loader, valid_loader,n_epochs=10)
    validation_accuracy = max(history["valid_metrics"])
    return validation_accuracy

In [ ]:
torch.manual_seed(42)
sampler = optuna.samplers.TPESampler(seed=42)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=5)

[I 2026-07-30 11:54:20,154] A new study created in memory with name: no-name-e8e30c83-3f4e-45ee-9ab5-118142aa1837


Epoch: 1/10,train loss:  2.2769,train metric: 0.1471,valid metric: 0.1860
Epoch: 2/10,train loss:  2.2093,train metric: 0.2794,valid metric: 0.3500
Epoch: 3/10,train loss:  2.1164,train metric: 0.4110,valid metric: 0.4554
Epoch: 4/10,train loss:  1.9776,train metric: 0.5137,valid metric: 0.5562
Epoch: 5/10,train loss:  1.7867,train metric: 0.5827,valid metric: 0.6026
Epoch: 6/10,train loss:  1.5775,train metric: 0.6184,valid metric: 0.6228
Epoch: 7/10,train loss:  1.3978,train metric: 0.6288,valid metric: 0.6326
Epoch: 8/10,train loss:  1.2605,train metric: 0.6360,valid metric: 0.6372
Epoch: 9/10,train loss:  1.1572,train metric: 0.6468,valid metric: 0.6424


[I 2026-07-30 11:58:24,626] Trial 0 finished with value: 0.6435999870300293 and parameters: {'learning_rate': 0.00031489116479568613, 'n_hidden': 287}. Best is trial 0 with value: 0.6435999870300293.


Epoch: 10/10,train loss:  1.0782,train metric: 0.6537,valid metric: 0.6436
Epoch: 1/10,train loss:  1.1459,train metric: 0.6228,valid metric: 0.7338
Epoch: 2/10,train loss:  0.6108,train metric: 0.7841,valid metric: 0.7994
Epoch: 3/10,train loss:  0.5203,train metric: 0.8171,valid metric: 0.8090
Epoch: 4/10,train loss:  0.4810,train metric: 0.8303,valid metric: 0.8310
Epoch: 5/10,train loss:  0.4558,train metric: 0.8403,valid metric: 0.8352
Epoch: 6/10,train loss:  0.4388,train metric: 0.8460,valid metric: 0.8444
Epoch: 7/10,train loss:  0.4240,train metric: 0.8511,valid metric: 0.8412
Epoch: 8/10,train loss:  0.4124,train metric: 0.8564,valid metric: 0.8512
Epoch: 9/10,train loss:  0.3999,train metric: 0.8597,valid metric: 0.8530


[I 2026-07-30 12:02:26,523] Trial 1 finished with value: 0.8539999723434448 and parameters: {'learning_rate': 0.008471801418819975, 'n_hidden': 188}. Best is trial 1 with value: 0.8539999723434448.


Epoch: 10/10,train loss:  0.3897,train metric: 0.8637,valid metric: 0.8540
Epoch: 1/10,train loss:  2.3069,train metric: 0.1144,valid metric: 0.1082
Epoch: 2/10,train loss:  2.2993,train metric: 0.1231,valid metric: 0.1294
Epoch: 3/10,train loss:  2.2914,train metric: 0.1606,valid metric: 0.1710
Epoch: 4/10,train loss:  2.2836,train metric: 0.1839,valid metric: 0.1840
Epoch: 5/10,train loss:  2.2762,train metric: 0.1891,valid metric: 0.1856
Epoch: 6/10,train loss:  2.2692,train metric: 0.1910,valid metric: 0.1898
Epoch: 7/10,train loss:  2.2623,train metric: 0.1933,valid metric: 0.1932
Epoch: 8/10,train loss:  2.2554,train metric: 0.2000,valid metric: 0.2022
Epoch: 9/10,train loss:  2.2485,train metric: 0.2122,valid metric: 0.2160


[I 2026-07-30 12:05:54,501] Trial 2 finished with value: 0.23340000212192535 and parameters: {'learning_rate': 4.207988669606632e-05, 'n_hidden': 63}. Best is trial 1 with value: 0.8539999723434448.


Epoch: 10/10,train loss:  2.2414,train metric: 0.2299,valid metric: 0.2334
Epoch: 1/10,train loss:  2.3035,train metric: 0.1373,valid metric: 0.1526
Epoch: 2/10,train loss:  2.3005,train metric: 0.1569,valid metric: 0.1724
Epoch: 3/10,train loss:  2.2975,train metric: 0.1755,valid metric: 0.1896
Epoch: 4/10,train loss:  2.2945,train metric: 0.1941,valid metric: 0.2132
Epoch: 5/10,train loss:  2.2914,train metric: 0.2105,valid metric: 0.2288
Epoch: 6/10,train loss:  2.2884,train metric: 0.2261,valid metric: 0.2418
Epoch: 7/10,train loss:  2.2853,train metric: 0.2419,valid metric: 0.2580
Epoch: 8/10,train loss:  2.2823,train metric: 0.2581,valid metric: 0.2742
Epoch: 9/10,train loss:  2.2792,train metric: 0.2736,valid metric: 0.2918


[I 2026-07-30 12:09:14,001] Trial 3 finished with value: 0.30959999561309814 and parameters: {'learning_rate': 1.7073967431528103e-05, 'n_hidden': 263}. Best is trial 1 with value: 0.8539999723434448.


Epoch: 10/10,train loss:  2.2761,train metric: 0.2897,valid metric: 0.3096
Epoch: 1/10,train loss:  1.8379,train metric: 0.4869,valid metric: 0.6208
Epoch: 2/10,train loss:  0.9751,train metric: 0.6666,valid metric: 0.6978
Epoch: 3/10,train loss:  0.7608,train metric: 0.7253,valid metric: 0.7416
Epoch: 4/10,train loss:  0.6704,train metric: 0.7639,valid metric: 0.7720
Epoch: 5/10,train loss:  0.6108,train metric: 0.7913,valid metric: 0.7904
Epoch: 6/10,train loss:  0.5686,train metric: 0.8054,valid metric: 0.8052
Epoch: 7/10,train loss:  0.5385,train metric: 0.8164,valid metric: 0.8082
Epoch: 8/10,train loss:  0.5158,train metric: 0.8243,valid metric: 0.8214
Epoch: 9/10,train loss:  0.4988,train metric: 0.8281,valid metric: 0.8220


[I 2026-07-30 12:12:25,317] Trial 4 finished with value: 0.8220000267028809 and parameters: {'learning_rate': 0.002537815508265664, 'n_hidden': 218}. Best is trial 1 with value: 0.8539999723434448.


Epoch: 10/10,train loss:  0.4842,train metric: 0.8330,valid metric: 0.8092


In [ ]:
study.best_params

{'learning_rate': 0.008471801418819975, 'n_hidden': 188}

In [ ]:
study.best_value

0.8539999723434448

In [ ]:
def objective(trial, train_loader, valid_loader):
    learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-1, log=True)
    n_hidden = trial.suggest_int("n_hidden", 20, 300)
    model = ImageClassifier(n_inputs=1 * 28 * 28, n_hidden1=n_hidden,
                            n_hidden2=n_hidden, n_classes=10).to(device)
    optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
    xentropy = nn.CrossEntropyLoss()
    accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=10)
    accuracy = accuracy.to(device)
    best_validation_accuracy = 0.0
    for epoch in range(n_epochs):
        history = train2(model, optimizer, xentropy, accuracy, train_loader,
                         valid_loader, n_epochs =1)
        validation_accuracy = max(history["valid_metrics"])
        if validation_accuracy > best_validation_accuracy:
            best_validation_accuracy = validation_accuracy
        trial.report(validation_accuracy, epoch)
        if trial.should_prune():
            raise optuna.TrialPruned()
    return best_validation_accuracy

In [ ]:
objective_with_data = lambda trial: objective(
    trial, train_loader=train_loader, valid_loader=valid_loader)

In [ ]:
from functools import partial

objective_with_data = partial(objective, train_loader=train_loader,
                              valid_loader=valid_loader)


In [ ]:
torch.manual_seed(42)
sampler = optuna.samplers.TPESampler(seed=42)
pruner = optuna.pruners.MedianPruner()
study = optuna.create_study(direction="maximize", sample=sampler,
                            pruner=pruner)
study.optimize(objective_with_data, n_trials=20)

In [ ]:
study.best_value

In [ ]:
study.best_params

Saving and Loading a Pytorch Model

In [ ]:
torch.save(model, "my_fashion_mnist.pt")


In [ ]:
loaded_model = torch.load("my_fashion_mnist.pt", weights_only=False)

In [ ]:
loaded_model.eval()
y_pred_logits = loaded_model(X_new)

In [ ]:
torch.save(model.state_dict(), "my_fashion_mnist_weights.pt")

In [ ]:
type(model.state_dict())

collections.OrderedDict

In [ ]:
new_model = ImageClassifier(n_inputs=1 * 28 * 28, n_hidden1=300, n_hidden2=100,
                            n_classes=10)
loaded_weights = torch.load("my_fashion_mnist_weights.pt", weights_only=True)
new_model.load_state_dict(loaded_weights)
new_model.eval()

ImageClassifier(
  (mlp): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Linear(in_features=784, out_features=300, bias=True)
    (2): ReLU()
    (3): Linear(in_features=300, out_features=100, bias=True)
    (4): ReLU()
    (5): Linear(in_features=100, out_features=10, bias=True)
  )
)

In [ ]:
model_data = {
    "model_state_dict": model.state_dict(),
    "model_hyperparameters": {
        "n_inputs": 1 * 28 * 28,
        "n_hidden1": 300,
        "n_hidden2": 100,
        "n_classes": 10,
    }
}
torch.save(model_data, "my_fashion_mnist_model.pt")

In [ ]:
loaded_data = torch.load("my_fashion_mnist_model.pt", weights_only=True)
new_model = ImageClassifier(**loaded_data["model_hyperparameters"])
new_model.load_state_dict(loaded_data["model_state_dict"])
new_model.eval()

ImageClassifier(
  (mlp): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Linear(in_features=784, out_features=300, bias=True)
    (2): ReLU()
    (3): Linear(in_features=300, out_features=100, bias=True)
    (4): ReLU()
    (5): Linear(in_features=100, out_features=10, bias=True)
  )
)

Compiling and Optimizing a PyTorch Model

In [ ]:
torchscript_model = torch.jit.trace(model, X_new)


In [ ]:
torchscript_model = torch.jit.script(model)

In [ ]:
optimized_model = torch.jit.optimize_for_inference(torchscript_model)

In [ ]:
optimized_model.save("my_fashion_mnist_torchscript.pt")

In [ ]:
loaded_torchscript_model = torch.jit.load("my_fashion_mnist_torchscript.pt")

In [ ]:
y_pred_logits = loaded_torchscript_model(X_new)
y_pred_logits

tensor([[ -4.2464,   0.1064,  -5.6586,  -2.2965,  -2.5489,   1.5029,  -3.2325,
          10.6315,  -1.1583,   7.4496],
        [ -0.3973,  -2.5875,  11.4448,  -1.3141,  16.8719, -13.4651,   6.8998,
         -11.6993,   0.4704,  -7.8363],
        [ -0.1328,  -1.7205,   5.1705,   0.1916,   3.5592,  -4.5485,   3.6931,
          -3.6608,  -0.1050,  -2.5322]], device='cuda:0')

In [ ]:
compiled_model = torch.compile(model,)

In [ ]:
import os
import torch

# Force PyTorch to disable the Triton/Dynamo compiler
os.environ["TORCHDYNAMO_DISABLE"] = "1"
torch._dynamo.config.suppress_errors = True
X_new = X_new.to(device)
if device == "cuda":
    y_pred_logit = compiled_model(X_new)

In [ ]:
y_pred_logit

tensor([[ -4.2464,   0.1064,  -5.6586,  -2.2965,  -2.5489,   1.5029,  -3.2325,
          10.6315,  -1.1583,   7.4496],
        [ -0.3973,  -2.5875,  11.4448,  -1.3141,  16.8719, -13.4651,   6.8998,
         -11.6993,   0.4704,  -7.8363],
        [ -0.1328,  -1.7205,   5.1705,   0.1916,   3.5592,  -4.5485,   3.6931,
          -3.6608,  -0.1050,  -2.5322]], device='cuda:0',
       grad_fn=<AddmmBackward0>)